version: '2'
services:
    db:
        build: ./db
        ports:
            - "5432:5432"
        #command: /bin/bash -c "while true; do sleep 5; done"
        networks:
            - dev-network
        environment:
            - POSTGRES_PASSWORD=postgres

    app:
        build: ./app
        volumes:
            - ./app:/code/
        # command: /root/init_container.sh
        ports:
            - "81:80"
        networks:
            - dev-network

    web:
        build: ./web
        volumes:
            - ./web:/usr/share/nginx/html:ro
        ports:
            - "80:80"
        networks:
            - dev-network


networks:
    dev-network:
        driver: bridge
